# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('edad', models.PositiveIntegerField()),
                ('dni', models.CharField(max_length=8)),
                ('genero', models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino')], max_length=15)),
                ('domicilio', models.CharField(max_length=150)),
                ('barrio', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150)),
                ('provincia', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('lugar_de_nacimiento', models.CharField(max_length=150)),
                ('obraSocial', models.BooleanField(default=True)),
                ('hermanos', models.ManyToManyField(null=True, related_name='_postulante_hermanos_+', to='preinscripcion.Postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('edad', models.PositiveIntegerField()),
                ('dni', models.CharField(max_length=8)),
                ('cuil', models.CharField(max_length=11, null=True)),
                ('genero', models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino')], max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.CharField(max_length=150)),
                ('barrio', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150)),
                ('provincia', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('obraSocial', models.BooleanField(default=True)),
                ('nivelAcademico', models.CharField(max_length=150)),
                ('ocupacion', models.CharField(max_length=150)),
                ('horarioLaboral', models.CharField(max_length=150)),
                ('telefonoPersonal', models.CharField(max_length=30)),
                ('telefonoLaboral', models.CharField(max_length=30, null=True)),
                ('razonSocial', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postulante',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madre', to='preinscripcion.Responsable'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='preinscripcion.Responsable'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='preinscripcion.Responsable'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='vive_con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vive_con', to='preinscripcion.Responsable'),
        ),
    ]
