# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='nacionalidad',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='hermanos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_postulante_hermanos_+', to='preinscripcion.Postulante'),
        ),
    ]
