# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='cant_notas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
