# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
