# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura_ciclo', models.DateField()),
                ('fecha_cierre_ciclo', models.DateField()),
                ('fecha_inicio_preinsc_ni', models.DateTimeField()),
                ('fecha_fin_preinsc_ni', models.DateTimeField()),
                ('vacantes', models.PositiveIntegerField()),
                ('ultimo_nro_sorteo', models.PositiveIntegerField(default=0)),
                ('fecha_dia_sorteo', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Preinscripcion4Anios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('nro_de_preinscripto', models.CharField(max_length=10, unique=True)),
                ('nro_de_sorteo', models.PositiveIntegerField(unique=True)),
                ('estado', models.CharField(choices=[('PREINSCRIPTO', 'Preinscripto'), ('CONFIRMADO', 'Confirmado'), ('DESCARTADO', 'Descartado'), ('AUSENTE', 'Ausente'), ('RECHAZADO', 'Rechazado'), ('ALUMNO', 'Alumno')], default='PREINSCRIPTO', max_length=20)),
                ('cicloLectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.CicloLectivo')),
            ],
        ),
        migrations.CreateModel(
            name='PreinscripcionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('nro_de_preinscripto', models.CharField(max_length=10, unique=True)),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario')], default='INICIAL', max_length=20)),
                ('grado', models.PositiveIntegerField(max_length=1)),
                ('confirmado', models.BooleanField(default=False)),
                ('cubrio_vacante', models.BooleanField(default=False)),
                ('cicloLectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.CicloLectivo')),
            ],
        ),
        migrations.AlterField(
            model_name='postulante',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='hermanos',
            field=models.ManyToManyField(related_name='_postulante_hermanos_+', to='preinscripcion.Postulante'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.Postulante'),
        ),
        migrations.AddField(
            model_name='preinscripcion4anios',
            name='postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.Postulante'),
        ),
    ]
