# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0002_auto_20170620_0129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostulanteLimpio',
            new_name='PostulanteConfirmado',
        ),
    ]
