# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0002_auto_20170530_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripciongeneral',
            name='grado',
            field=models.PositiveIntegerField(),
        ),
    ]
