# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0002_preinscripciongeneral_cant_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscripciongeneral',
            name='cant_notas',
        ),
    ]
