# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0003_auto_20170623_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion4anios',
            name='fecha_confirmado',
            field=models.DateField(null=True),
        ),
    ]
