# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0003_auto_20170620_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hermano',
        ),
    ]
