# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0003_auto_20170530_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='lugar_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='obraSocial',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='horarioLaboral',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='nivelAcademico',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='obraSocial',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='razonSocial',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='telefonoLaboral',
        ),
    ]
