# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0003_remove_preinscripciongeneral_cant_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='telefonoPersonal',
            field=models.CharField(default='3624', max_length=30),
        ),
    ]
