# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preinscripcion', '0004_preinscripcion4anios_fecha_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion4anios',
            name='responsablequeconfirma',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion4anios',
            name='usuarioqueconfirma',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preinscripcion4anios',
            name='fecha_confirmado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
