# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0004_auto_20171011_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion4anios',
            name='puntaje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='puntaje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
