# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0004_auto_20170609_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='hermanos',
            field=models.ManyToManyField(blank=True, related_name='_postulante_hermanos_+', to='preinscripcion.Postulante'),
        ),
    ]
