# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0005_auto_20170609_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='genero',
            field=models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino')], default='MASCULINO', max_length=15),
        ),
        migrations.AlterField(
            model_name='preinscripcion4anios',
            name='nro_de_sorteo',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
