# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import preinscripcion.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preinscripcion', '0005_auto_20170908_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscripciongeneral',
            name='postulante',
        ),
        migrations.AddField(
            model_name='postulante',
            name='pg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.PreinscripcionGeneral'),
        ),
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='estado',
            field=models.CharField(choices=[('PREINSCRIPTO', 'Preinscripto'), ('CONFIRMADO', 'Confirmado'), ('DESCARTADO', 'Descartado'), ('AUSENTE', 'Ausente'), ('RECHAZADO', 'Rechazado'), ('ALUMNO', 'Alumno')], default='PREINSCRIPTO', max_length=20),
        ),
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='fecha_confirmado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='responsablequeconfirma',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='usuarioqueconfirma',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preinscripciongeneral',
            name='grado',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='preinscripciongeneral',
            name='nivel',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario')], default='INICIAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='preinscripciongeneral',
            name='nro_de_preinscripto',
            field=models.CharField(default=preinscripcion.models.id_generator, max_length=10, unique=True),
        ),
    ]
