# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0006_auto_20170908_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='motivo',
            field=models.TextField(default='No contesta'),
        ),
    ]
