# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0007_auto_20170610_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='vive_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vive_con', to='preinscripcion.Responsable'),
        ),
    ]
