# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0008_auto_20170610_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='hermanos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_postulante_hermanos_+', to='preinscripcion.Postulante'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='madre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='madre', to='preinscripcion.Responsable'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='preinscripcion.Responsable'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='preinscripcion.Responsable'),
        ),
    ]
