# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-10 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0008_auto_20170908_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion4anios',
            name='usuarioqueconfirma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preinscripciongeneral',
            name='usuarioqueconfirma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
