# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0009_auto_20170910_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripciongeneral',
            name='institucionanterior',
            field=models.CharField(default='Escuela anterior', max_length=200),
        ),
    ]
