# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0009_auto_20170610_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
