# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0010_preinscripciongeneral_institucionanterior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preinscripciongeneral',
            old_name='institucionanterior',
            new_name='institucion_anterior',
        ),
    ]
