# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0010_auto_20170610_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion4anios',
            name='motivo',
            field=models.TextField(default='No contesta'),
        ),
    ]
