# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0011_auto_20170911_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preinscripciongeneral',
            old_name='grado',
            new_name='anio',
        ),
    ]
