# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0011_preinscripcion4anios_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion4anios',
            name='nro_de_sorteo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
