# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0012_auto_20170610_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion4anios',
            name='cicloLectivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.CicloLectivo'),
        ),
        migrations.AlterField(
            model_name='preinscripcion4anios',
            name='postulante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.Postulante'),
        ),
    ]
