# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0013_auto_20170610_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion4anios',
            name='postulante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to='preinscripcion.Postulante'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='dni',
            field=models.CharField(default='12345678', max_length=8),
        ),
    ]
