# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0014_auto_20170610_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='dni',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='preinscripcion4anios',
            name='postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to='preinscripcion.Postulante'),
        ),
    ]
