# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0015_auto_20170610_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscripcion4anios',
            name='postulante',
        ),
        migrations.AddField(
            model_name='postulante',
            name='preinscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.Preinscripcion4Anios'),
        ),
    ]
