# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0017_auto_20170610_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulanteLimpio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('dni', models.CharField(max_length=8)),
                ('genero', models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino')], default='MASCULINO', max_length=15)),
                ('domicilio', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('hermanos', models.ManyToManyField(blank=True, null=True, related_name='_postulantelimpio_hermanos_+', to='preinscripcion.PostulanteLimpio')),
                ('madre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='madrel', to='preinscripcion.Responsable')),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padrel', to='preinscripcion.Responsable')),
                ('preinscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.Preinscripcion4Anios')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorl', to='preinscripcion.Responsable')),
                ('vive_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vive_conl', to='preinscripcion.Responsable')),
            ],
        ),
    ]
