# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0018_postulantelimpio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='hermanos',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='madre',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='preinscripcion',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='postulantelimpio',
            name='vive_con',
        ),
        migrations.AddField(
            model_name='postulantelimpio',
            name='postulante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.Postulante'),
        ),
        migrations.AlterField(
            model_name='postulantelimpio',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
