# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0019_auto_20170610_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
