# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0021_auto_20170612_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='postulante',
            name='hermanos',
            field=models.ManyToManyField(blank=True, null=True, to='preinscripcion.Hermano'),
        ),
    ]
