# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0024_auto_20170614_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclolectivo',
            name='fecha_dia_sorteo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ciclolectivo',
            name='fecha_fin_preinsc_ni',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ciclolectivo',
            name='fecha_inicio_preinsc_ni',
            field=models.DateField(),
        ),
    ]
