# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preinscripcion', '0001_initial'),
        ('mes', '0004_auto_20170925_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaP',
            fields=[
                ('nota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mes.Nota')),
                ('p4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.Preinscripcion4Anios')),
                ('pg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.PreinscripcionGeneral')),
            ],
            bases=('mes.nota',),
        ),
    ]
