# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0006_notag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notap',
            name='p4',
        ),
        migrations.AddField(
            model_name='nota',
            name='remitente',
            field=models.CharField(default='Don Pedro', max_length=200),
        ),
    ]
