# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import mes.models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0007_auto_20170925_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nro_de_tracking',
            field=models.CharField(default=mes.models.id_generator, max_length=10),
        ),
    ]
