# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0009_nota_notificar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaG',
        ),
    ]
