# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0010_auto_20170929_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='motivo',
            field=models.CharField(default='No me acuerdo', max_length=200),
        ),
    ]
