# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0011_nota_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='motivo_derivar',
            field=models.CharField(default='No me corresponde', max_length=200),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estado',
            field=models.CharField(choices=[('NUEVA', 'Nueva'), ('RECIBIDA', 'Recibida'), ('EN TR\xc1MITE', 'En tramite'), ('DERIVADA', 'Derivada'), ('RECHAZADA', 'Rechazada')], default='NUEVA', max_length=100),
        ),
    ]
