# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0012_auto_20171002_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='estado',
            field=models.CharField(choices=[('NUEVA', 'Nueva'), ('RECIBIDA', 'Recibida'), ('EN TRAMITE', 'En tr\xe1mite'), ('DERIVADA', 'Derivada'), ('RECHAZADA', 'Rechazada')], default='NUEVA', max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='motivo_derivar',
            field=models.CharField(default='', max_length=200),
        ),
    ]
