# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-03 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0013_auto_20171002_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='pg.Perfil'),
        ),
    ]
