# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-07 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0016_nota_emisor_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='emisor_perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor_perfil', to='pg.Perfil', verbose_name='Seleccione Perfil'),
        ),
    ]
