# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0018_auto_20171007_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='motivo_derivar',
        ),
    ]
