# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0020_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='receptor',
            new_name='destino',
        ),
    ]
