# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0004_auto_20171004_1604'),
        ('mes', '0021_auto_20171011_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='emisor_perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor_perfil', to='pg.Perfil'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='emisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor_mov', to=settings.AUTH_USER_MODEL),
        ),
    ]
