# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0022_auto_20171011_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='emisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor_der', to=settings.AUTH_USER_MODEL),
        ),
    ]
