# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0023_auto_20171011_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='emisor_perfil',
        ),
    ]
