# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0004_auto_20171004_1604'),
        ('mes', '0024_remove_movimiento_emisor_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='emisor_perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisorper_der', to='pg.Perfil'),
        ),
    ]
