# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0025_movimiento_emisor_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='remitente',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
