# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0026_auto_20171011_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='notai',
            name='nota_fisica',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estado',
            field=models.CharField(choices=[('NUEVA', 'Nueva'), ('RECIBIDA', 'Recibida'), ('EN TRAMITE', 'En tr\xe1mite'), ('DERIVADA', 'Derivada'), ('RECHAZADA', 'Rechazada'), ('DESPACHADA', 'Despachada')], default='NUEVA', max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='motivo',
            field=models.CharField(default='Consulta', max_length=400),
        ),
    ]
