# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0028_auto_20171028_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notai',
            name='nota_fisica',
            field=models.BooleanField(default=False),
        ),
    ]
