# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0030_auto_20171030_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notai',
            name='asunto',
        ),
        migrations.AddField(
            model_name='nota',
            name='asunto',
            field=models.CharField(default='Asunto.', max_length=100),
        ),
    ]
