# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_auto_20171003_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='perfil',
            field=models.CharField(choices=[('REP LEGAL', 'Representante Legal'), ('ADMINSTRACION', 'Administracion'), ('CONTABLE', 'Contable'), ('COBRANZA', 'Cobranza'), ('SECRETARIA', 'Secretaria'), ('INFORMATICA', 'Informatica'), ('MESA DE ENTRADA', 'Mesa de entrada'), ('ESCUELA', 'Escuela'), ('INICIAL', 'Inicial'), ('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario'), ('BIBLIOTECA', 'Biblioteca'), ('PARROQUIA', 'Parroquia')], default='', max_length=30),
        ),
    ]
